version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "example/packages.dhall" }}-{{ checksum "example/package.json" }}

      - run:
          working_directory: example
          command: |
            git checkout -b gh-pages
            git reset --hard origin/master
            yarn add --dev parcel purescript spago
            yarn build
            git checkout -- package.json

      - save_cache:
          paths:
            - example/.spago
            - example/node_modules
            - example/output
          key: deps-{{ checksum "example/packages.dhall" }}-{{ checksum "example/package.json" }}

      - run:
          command: |
            cp docs/* .
            git config user.email "remotenonsense@gmail.com"
            git config user.name "CircleCI"
            git add . && git commit -am 'build gh-pages'
            # https://stackoverflow.com/a/48763205
            git push -q -f https://${GH_PAGES_TOKEN}@github.com/nonbili/purescript-nonbili-dom.git gh-pages

workflows:
  build-gh-pages:
    jobs:
      - build:
          context: gh-pages
          filters:
            branches:
              only:
                - master
